name: Deploy to Production and Develop

on:
  push:
    branches:
      - main
      - Develop

jobs:
  build-and-deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    env:
      REACT_APP_API_URL: https://holmesbooking.com

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to hosting service by ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: win5219.site4now.net
          username: front
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build

  build-and-deploy-development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Develop'

    env:
      REACT_APP_API_URL: http://holmessoftware-001-site2.atempurl.com

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to hosting service by ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: win5219.site4now.net
          username: development
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build
