name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to hosting service
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: win5219.site4now.net
          username: front
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build

